name: Calendar Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'services/calendar-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/calendar-service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/calendar-service

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: services/calendar-service/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Build
      run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4

    # Add deployment steps here based on your infrastructure
    # Examples:
    # - Deploy to AWS ECS
    # - Deploy to Google Cloud Run
    # - Deploy to Azure App Service